### PR TITLE
Log Electron version

### PR DESCRIPTION
**Pull request by zzarcon**
Closes https://github.com/Jam3/devtool/issues/52

### CODE REVIEW

**Comment by mattdesl** [comment]
Thanks for the PR! :smile:

`process.version` in the Electron server is actually the Node version being used by Electron. Electron exposes that as a number with `process.versions.node`.

So maybe we could do this to clarify:

```js
console.log('devtool ' + require('./package.json').version);
console.log('electron ' + process.versions.electron);
console.log('node ' + process.versions.node);
console.log('chrome ' + process.versions.chrome);
```

**Comment by zzarcon** [comment]
@mattdesl good point! thanks for the help ^^. Changes applied.

**Comment by mattdesl** [comment]
Thanks, pushed to npm!

**Comment by MadLittleMods** [comment]
Sorry, for the "electron version" mistake. I knew it was the Node version(hence the recompile note) but wrote it wrong. Glad to see all this info now on `-v` :grinning:

**Pull request merged**
